stages:
  - build
  - deploy

build-job:
  rules:
   - if: $CI_COMMIT_BRANCH == "main"
  stage: build
  script:
    - bun install
    - bun run build
  artifacts:
    paths:
      - build

deploy-job:
  rules:
   - if: $CI_COMMIT_BRANCH == "main"
  stage: deploy
  environment: production
  script:
    - deploy.sh
